### ISSUE TITLE
cannot customize layout

### ISSUE THREAD

**Issue by c0d3-ninja** [delaroy/DragNDrop#1]
Starting of my app every time image goes to top left of the screen eventhough I give centerInParent. I want to customize it (Image view - center of the layout). I also try layoutParams.addRule(Relativelayout.CenterInParent,Relativelayout.TRUE) but If I used this Drag and drop was not working. Please give me a solution.

**Comment by sachinjavandroid** [comment]
What if I want to move image only in left,right,top and bottom border only as well as in the center.

For left and top I found the solution,but for right, bottom and center I am stuck and not getting any appropriate solution.

Do you have any solution to this problem?

**Comment by ghost** [comment]
Vimalchandhru instead of you use RelativeLayout.LayoutParams?
If you use this, try switching to FrameLayout.LayoutParams, it works differently, but might fix the problem.

`FrameLayout.LayoutParams objName = new FrameLayout.LayoutParams (150,150); `
`ObjName.gravity = Gravity.CENTER;`
(You can pass as a third parameter in the constructor the gravity you want, but I'd rather change it that way)
